import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import SearchForm from '../components/SearchForm'

const Home: NextPage = () => {
  return (
    <div className={styles.mainWrapper}>
      <Head>
        <title>language search tool</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <>
          <SearchForm />
        </>
      </main>
    </div>
  )
}

export default Home
